Update channels.csv
iptv-org/database pull request #14402
Opened 2024-11-24 14:36 UTC by hydrationn

### Description
- This PR updates the SBS channel information in the channel database, correcting existing data and enhancing details such as the logo, website, and broadcast categories.

### Related issue
- Edit SBS channel information #14425

2024-11-25 17:02 UTC, freearhey requested changes

2024-11-25 17:02 UTC, freearhey commented on data/channels.csv
> +SBS.kr,SBS,Seoul Broadcasting System,,,,KR,,,c/KR,kor,general,FALSE,,,,https://www.sbs.co.kr/,https://imgur.com/a/uHlt1Lv
```suggestion
SBS.kr,SBS,Seoul Broadcasting System,,,,KR,,,c/KR,kor,general,FALSE,,,,https://www.sbs.co.kr/,https://imgur.com/4LHX71N.png
```

2024-11-26 11:10 UTC, freearhey requested changes
To add information about SBS channel you need to edit the line with ID `SBSTV.kr` instead of creating a new entry.

2024-11-27 14:32 UTC, freearhey approved these changes

2024-11-27 15:15 UTC, hydrationn commented
@ProPontifex,
I’ve updated the code based on the feedback provided earlier regarding issue #14343. Could you please review the changes when you have time? Let me know if there are any additional adjustments needed. Thank you!

2024-11-27 15:53 UTC, BellezaEmporium commented on data/channels.csv
> +SBS.kr,SBS,Seoul Broadcasting System,,,,KR,,,c/KR,kor,general,FALSE,,,,https://www.sbs.co.kr/,https://imgur.com/a/uHlt1Lv
i.imgur.com*

2024-11-27 15:54 UTC, BellezaEmporium commented
Image link is broken, I believe it's "i.imgur.com", not "imgur.com"

2024-11-27 15:56 UTC, freearhey approved these changes

2024-11-27 15:57 UTC, hydrationn commented
> 이미지 링크가 끊어졌습니다. "imgur.com"이 아니라 "i.imgur.com"인 것 같습니다.

Thank you for your feedback, I've done the modification!

2024-11-27 17:05 UTC, BellezaEmporium approved these changes

2024-11-27 17:05 UTC, merged