Updates
iptv-org/database pull request #15101
Opened 2024-12-31 02:20 UTC by ProPontifex

See title

2024-12-31 03:33 UTC, freearhey commented on data/channels.csv
> +NobelTV.ua,Nobel TV,,,,UA,,Dnipro,c/UA,ukr,general,FALSE,2003-08-07,2023-06-05,,https://noble.tv/,https://i.imgur.com/yjAhb4w.png
Where did you find information that this channel is broadcast from Ukraine? The official website does not even mention the Ukrainian language:

![image](https://github.com/user-attachments/assets/133eea34-1f02-4b90-9a54-57511ad1a513)

https://noble.tv/

2024-12-31 03:44 UTC, freearhey commented on data/channels.csv
> +NoorinTV.af,Noorin TV,تلویزیون نورین,,Haji Mohammad Arif Noori,AF,,Kabul,c/AF,fas,general,FALSE,2007-01-01,2021-12-01,,https://www.noortv.af/,https://i.imgur.com/GKp7m0V.png
Are you sure "Noor TV" and "Noorin TV" aren't two different channels? 

There is no mention of any other name on Noor TV's YouTube channel: https://www.youtube.com/@NoorTV_af/videos

Also "Noorin TV" has its own YouTube channel (https://www.youtube.com/c/NoorinTv2/videos) and used to have a website (https://web.archive.org/web/20210818232841/https://noorintv.net/en).

2025-01-01 00:58 UTC, ProPontifex commented on data/channels.csv
> +NobelTV.ua,Nobel TV,,,,UA,,Dnipro,c/UA,ukr,general,FALSE,2003-08-07,2023-06-05,,https://noble.tv/,https://i.imgur.com/yjAhb4w.png
I see where I went rong, but with reason. There is indeed Noble.eg, but also Nobel.ua (https://27tv.dp.ua/) which, as of 2023, has apparently closed. Dnipro as the location threw me off. I'll correct this immediately.

2025-01-01 01:01 UTC, ProPontifex commented on data/channels.csv
> +NoorinTV.af,Noorin TV,تلویزیون نورین,,Haji Mohammad Arif Noori,AF,,Kabul,c/AF,fas,general,FALSE,2007-01-01,2021-12-01,,https://www.noortv.af/,https://i.imgur.com/GKp7m0V.png
Yes, you're right: there are two different channels. I'll make a request to add Noor TV to the iptv/database separately.

2025-01-01 06:26 UTC, freearhey requested changes
No need to add `NobleTV.eg` and `NoorTV.uk`, they are both already in the database. You only need to update your PR.

2025-01-02 00:37 UTC, ProPontifex commented
Done

2025-01-02 12:53 UTC, freearhey commented
The issue with `NoorTV.af` is still unresolved.

2025-01-02 12:54 UTC, freearhey requested changes
The issue with `NoorTV.af` is still unresolved

Edit: the channel is finished, here's proof

https://cpj.org/2024/04/taliban-shuts-down-broadcasters-noor-and-barya-seals-noor-offices/

2025-01-02 15:32 UTC, BellezaEmporium commented on data/channels.csv
> -NoorTV.af,Noor TV,,,,AF,,,c/AF,fas,general,FALSE,,,,https://www.noortv.af/,https://i.imgur.com/GKp7m0V.png
NoorTV.af,Noor TV,,,,AF,,,c/AF,fas,general,FALSE,,,,https://www.noortv.af/,https://i.imgur.com/GKp7m0V.png to be re-added

2025-01-03 04:11 UTC, ProPontifex commented on data/channels.csv
> -NoorTV.af,Noor TV,,,,AF,,,c/AF,fas,general,FALSE,,,,https://www.noortv.af/,https://i.imgur.com/GKp7m0V.png
Yes it has. The Taliban took it off the air: it's gone.

2025-01-03 08:20 UTC, freearhey commented on data/channels.csv
> -NoorTV.af,Noor TV,,,,AF,,,c/AF,fas,general,FALSE,,,,https://www.noortv.af/,https://i.imgur.com/GKp7m0V.png
In this case, you simply need to add the closing date.

2025-01-03 09:41 UTC, ProPontifex commented on data/channels.csv
> -NoorTV.af,Noor TV,,,,AF,,,c/AF,fas,general,FALSE,,,,https://www.noortv.af/,https://i.imgur.com/GKp7m0V.png
Added. Hopefully, now ready for approval.

2025-01-03 10:19 UTC, freearhey submitted a review, later dismissed

2025-01-03 10:21 UTC, BellezaEmporium approved these changes

2025-01-03 10:23 UTC, BellezaEmporium commented
Existing conflict... Will check.

2025-01-03 10:36 UTC, BellezaEmporium commented
Quick question though... why
WSVIDT2.vi
WSVIDT3.vi
WSVIDT4.vi

and 
WSVIDT1.*us* ?

That sounds quite illogical in my point of view. Same applies to :

KGTFDT1.us
KGTFDT2.gu

2025-01-03 12:28 UTC, ProPontifex commented
Then why have the Virgin Islands, Guam and Puerto Rico (US protectorates) as separate database entries in the first place? I'm just trying to correct the errors that were there from the get go. After all, the ISO standard DOES give these protectorates separate codes from the US. Frankly, it's up to the team, but I was just trying to apply some consistency.

2025-01-04 13:57 UTC, freearhey approved these changes

2025-01-04 17:41 UTC, Dum4G approved these changes

2025-01-04 17:41 UTC, merged