Update channels.csv
iptv-org/database pull request #1822
Opened 2023-01-14 02:56 UTC by riczuko

2023-01-14 12:37 UTC, freearhey requested changes

2023-01-14 12:37 UTC, freearhey commented on data/channels.csv
> +XEWTDT.mx,XEWT-TDT,,,Grupo Televisa,MX,,Tijuana,c/MX,spa,,FALSE,,,,https://xewt12.com/,https://static.wikia.nocookie.net/logopedia/images/1/16/XEWT_2018.png
```suggestion
XEWTTDT.mx,XEWT-TDT,,,Grupo Televisa,MX,,Tijuana,c/MX,spa,,FALSE,,,,https://xewt12.com/,https://static.wikia.nocookie.net/logopedia/images/1/16/XEWT_2018.png
```

2023-01-15 11:03 UTC, LaneSh4d0w commented
Tried to fix the issue, but I had no write access on this repo, sorry.

2023-01-15 11:03 UTC, LaneSh4d0w commented on data/channels.csv
> +XEWTDT.mx,XEWT-TDT,,,Grupo Televisa,MX,,Tijuana,c/MX,spa,,FALSE,,,,https://xewt12.com/,https://static.wikia.nocookie.net/logopedia/images/1/16/XEWT_2018.png
```suggestion
XEWTTDT.mx,XEWT-TDT,,,Grupo Televisa,MX,,Tijuana,c/MX,spa,,FALSE,,,,https://xewt12.com/,https://static.wikia.nocookie.net/logopedia/images/1/16/XEWT_2018.png

```

2023-01-15 11:18 UTC, freearhey commented
@LaneSh4d0w Please try again. The admin panel states that you have write access to all repositories in the organization.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/7253922/212537528-afb66f95-7c02-433e-a301-0534bd768e67.png">

2023-01-15 11:20 UTC, LaneSh4d0w commented
> @LaneSh4d0w Please try again. The admin panel states that you have write access to all repositories in the organization.
> 
> <img width="713" alt="image" src="https://user-images.githubusercontent.com/7253922/212537528-afb66f95-7c02-433e-a301-0534bd768e67.png">
> 

I do have access to all the projects, but the users when forking the repository can refuse collaborators to access it.

Please try to make the changes using the fork and github.dev, it gives me an error.

2023-01-15 11:43 UTC, freearhey commented
Now I see.

2023-01-15 21:07 UTC, closed without merging