Update channels.csv
iptv-org/database pull request #2351
Opened 2023-02-04 18:37 UTC by Tuyusero

id
ElSelloTV.com.ar

Channel Name
El SelloTV Madariaga

Alternative Names (optional)
No response

Network (optional)
No response

Owners (optional)
No response

Country
AR

Subdivision (optional)
AR-B

City (optional)
General Madariaga

Broadcast Area
s/AR-B

Languages
spa

Categories (optional)
no response

NSFW
FALSE

Launched (optional)
No response

Closed (optional)
No response

Replaced By (optional)
No response

Website (optional)
No response

Logo
https://elsellotv.com.ar/wp-content/uploads/2023/01/LogoTV23-920x613.png

Notes
No response

2023-02-04 18:55 UTC, Tuyusero commented
bug fixed in row 6108

2023-02-05 04:16 UTC, freearhey requested changes

2023-02-05 04:16 UTC, freearhey commented on data/channels.csv
> +ElSelloTVMadariaga.ar,El SelloTV Madariaga,,,Sello Group,AR,AR-B,General Madariaga,s/AR-B,spa,general,FALSE,,,,https://elsellotv.com.ar,https://elsellotv.com.ar/wp-content/uploads/2023/01/LogoTV23-92
```suggestion
ElSelloTVMadariaga.ar,El SelloTV Madariaga,,,Sello Group,AR,AR-B,General Madariaga,s/AR-B,spa,general,FALSE,,,,https://elsellotv.com.ar,https://i.imgur.com/bHaQqlB.png
```

Logo is too large: https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

2023-02-05 04:32 UTC, freearhey approved these changes

2023-02-05 04:34 UTC, merged