Add AlMashhad
iptv-org/database pull request #3759
Opened 2023-05-23 20:31 UTC by UltraHDR

2023-05-24 16:13 UTC, freearhey requested changes
Please update your request:

- the logo link is geoblocked

2023-05-24 21:05 UTC, UltraHDR commented
> Please update your request:
> 
>     * the logo link is geoblocked

Sorry, I don't have an alternative link and imgur upload is not working

2023-05-24 21:17 UTC, freearhey commented on data/channels.csv
> +AlMashhad.ae,Al Mashhad,,,,AE,,,c/AE,ara,,FALSE,,,,https://almashhad.com,https://almashhad.com/images/apple-touch-icon.png
```suggestion
AlMashhad.ae,Al Mashhad,,,,AE,,,c/AE,ara,,FALSE,,,,https://almashhad.com,https://i.imgur.com/6G6fxs5.png
```

2023-05-25 21:47 UTC, UltraHDR commented on data/channels.csv
> +AlMashhad.ae,Al Mashhad,,,,AE,,,c/AE,ara,,FALSE,,,,https://almashhad.com,https://almashhad.com/images/apple-touch-icon.png
@freearhey Thankyou

2023-05-25 22:11 UTC, freearhey approved these changes

2023-05-25 22:11 UTC, merged