Update channels.csv
iptv-org/database pull request #556
Opened 2022-09-30 02:57 UTC by Alstruit

References:
iptv-org/iptv#8985

2022-09-30 06:54 UTC, LaneSh4d0w submitted a review, later dismissed

2022-09-30 21:25 UTC, freearhey requested changes

2022-09-30 21:25 UTC, freearhey commented on data/channels.csv
> +LoveFMTv.bz,LoveFM TV,,,BZ,,,c/BZ,eng,news,FALSE,,,,https://lovefm.com/,https://i.imgur.com/UQcOkPA.png
```suggestion
LoveFMTV.bz,LoveFM TV,,,BZ,,,c/BZ,eng,news,FALSE,,,,https://lovefm.com/,https://i.imgur.com/UQcOkPA.png
```

2022-09-30 21:40 UTC, LaneSh4d0w approved these changes

2022-10-01 09:13 UTC, freearhey approved these changes

2022-10-01 09:13 UTC, merged